name: University Advisor Finder CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean compile --file pom.xml

    # Run tests with H2 in-memory database (simpler and more reliable for CI)
    - name: Run Tests with H2
      run: mvn -B test --file pom.xml -Dspring.profiles.active=test

    # Generate reports
    - name: Generate test reports
      if: always()
      run: mvn -B surefire-report:report-only site -DgenerateReports=false

    # Store test results
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: target/site/surefire-report.html